### ISSUE TITLE
Doing a few searches hits the GitHub API rate limit 

### ISSUE THREAD

**Issue by rly** [nwb-extensions/nwb-extensions.github.io#12]
The search function makes several API calls at once. The unauthenticated rate limit is 60 requests per hour from an IP address. This is quickly hit after a few searches on the extensions catalog (or during testing...)

See https://developer.github.com/v3/#rate-limiting

**Comment by rly** [comment]
Currently, each load of the main page makes 2N + 1 requests to the GitHub API, where N is the number of extensions in the Catalog.

**Comment by kir0ul** [comment]
Indeed, I can't find any extensions after only a few (not many) searches, I get a 403 error :confused: 

![image](https://github.com/nwb-extensions/nwb-extensions.github.io/assets/6053592/efd6f4f3-f9bc-4ef7-9305-6fff9c4c81f8)

**Comment by rly** [comment]
Fixed by #17
