### ISSUE TITLE
strange behavior from search

### ISSUE THREAD

**Issue by bendichter** [nwb-extensions/nwb-extensions.github.io#8]
searching "miniscope" does not work but searching "miniscop" does.

![image](https://user-images.githubusercontent.com/844306/68130471-b1945900-ff1b-11e9-9606-39ca9f83809a.png)

![image](https://user-images.githubusercontent.com/844306/68130495-bc4eee00-ff1b-11e9-9862-1b8636990d19.png)

**Comment by rly** [comment]
Fixed by #17
